@page = 1
@size = 2
@sort = displayName asc
@search = code.contains("5")

GET {{apiUrl}}/{{tenantId}}/products?page={{page}}&size={{size}}&sort={{sort}}&search={{search}}
Content-Type: application/json
